[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fandb"
dynamic = ["version", "license"]
description = 'PyTorch native distributed training for education.'
readme = "README.md"
requires-python = ">=3.11"
keywords = []
authors = [
  { name = "Chenchao Zhao", email = "35147961+ChenchaoZhao@users.noreply.github.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = []

[project.urls]
Documentation = "https://github.com/Chenchao Zhao/fandb#readme"
Issues = "https://github.com/Chenchao Zhao/fandb/issues"
Source = "https://github.com/Chenchao Zhao/fandb"

[tool.hatch.version]
path = "src/fandb/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/fandb tests}"

[tool.coverage.run]
source_pkgs = ["fandb", "tests"]
branch = true
parallel = true
omit = [
  "src/fandb/__about__.py",
]

[tool.coverage.paths]
fandb = ["src/fandb", "*/fandb/src/fandb"]
tests = ["tests", "*/fandb/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
